### ISSUE TITLE
[bug] /stock show will print the whole month

### ISSUE THREAD

**Issue by KageRyo** [Cutespirit-Team/CutespiritDiscordBot#4]
For example input : `/stock show 20220930 2884` _(20220930 玉山金)_ will print 20220901 to 20220930.
However, if input : `/stock show 20220929 2884`, the output will also print 20220901 to 20220930.

**Comment by mmm25002500** [comment]
Thanks for your feedback.
I fixed the bug in [Cutespirit-Team/NutcDiscordBot](https://github.com/Cutespirit-Team/NutcDiscordBot).
And I just add the feature of showing error message when the stock code not found.
